before_script:
  - echo "Before script"
  - export PATH="$PATH:/home/gitlab-runner/.nvm/versions/node/v22.11.0/bin"

stages:
  - build
  - deploy

variables:
  SSH_USER: prod-ca-mg
  SSH_HOST: 103.150.100.141
  SSH_PORT: 20102
  APP_DIR: /www/wwwroot/client_admin

build_prod:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public/build
    expire_in: 30 days
  only:
    - tags

deploy_dev:
  stage: deploy
  script:
    - cd /www/wwwroot/client-admin.mg.vexatechno.com #your project path
    - git pull
    - npm run build
    - composer install
    - php artisan migrate
    - php artisan optimize
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

deploy_prod:
  stage: deploy
  dependencies:
    - build_prod
  script:
    - scp -r -P $SSH_PORT public/build $SSH_USER@$SSH_HOST:$APP_DIR/public
    - SSH $SSH_USER@$SSH_HOST -p $SSH_PORT "cd $APP_DIR && git pull && php artisan optimize"
  only:
    - tags
