before_script:
  - echo "Before script"

variables:
  SSH_USER: prod-ca-mg
  SSH_HOST: 103.150.100.141
  SSH_PORT: 20102
  APP_DIR: /www/wwwroot/client_admin

deploy_dev:
  stage: build
  script:
    - cd /www/wwwroot/client-admin.mg.vexatechno.com #your project path
    - git pull
    - composer install
    - php artisan migrate
    - php artisan optimize
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always

deploy_prod:
  stage: deploy
  script:
    - SSH $SSH_USER@$SSH_HOST -p $SSH_PORT "cd $APP_DIR && git pull && php artisan optimize"
  only:
    - tags
